# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Argmax < Formula
  desc "Terminal-resident command completion and prediction"
  homepage "https://github.com/rselbach/argmax"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/rselbach/argmax/releases/download/v0.1.0/argmax_darwin_amd64.tar.gz"
      sha256 "ffb3602fee29a722ac5c712dca98c904ebd25f146255603fa52ef13f45df19b8"

      def install
        bin.install "argmax"
      end
    end
    on_arm do
      url "https://github.com/rselbach/argmax/releases/download/v0.1.0/argmax_darwin_arm64.tar.gz"
      sha256 "89e3d050c394f588a19ff96ed2cb84003f94d7670406dab43e76f5ecba99906c"

      def install
        bin.install "argmax"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rselbach/argmax/releases/download/v0.1.0/argmax_linux_amd64.tar.gz"
        sha256 "98c184b30cf6ee3d5b1424c852137c002117fce1659844373813730de22ed817"

        def install
          bin.install "argmax"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rselbach/argmax/releases/download/v0.1.0/argmax_linux_arm64.tar.gz"
        sha256 "b651425fa2efdb0acfc2846c393ce6e4ebe16b0b9c5ebf8f8605870a059c8efb"

        def install
          bin.install "argmax"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run "argmax setup" to install shell integration, and
      "argmax uninstall" before removing the package.
    EOS
  end
end
