# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwtdebug < Formula
  desc "A command line tool to decode, verify and generate JWTs (JSON Web Tokens)."
  homepage "https://github.com/rselbach/jwtdebug"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rselbach/jwtdebug/releases/download/v1.2.2/jwtdebug_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "8d4bc84c209089523647f08a0767b18834d93a5b461225a58315c5ac77b3e018"

      define_method(:install) do
        bin.install "jwtdebug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rselbach/jwtdebug/releases/download/v1.2.2/jwtdebug_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f19f3f25b11b4d76c7770e686eae3b34824c99047d5ed5ec8778625d53211b35"

      define_method(:install) do
        bin.install "jwtdebug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/jwtdebug/releases/download/v1.2.2/jwtdebug_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "9b4d61c50254b88e0371c2cd029823a81f88c018db27ee1008d2625ea4b44d0b"
      define_method(:install) do
        bin.install "jwtdebug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/jwtdebug/releases/download/v1.2.2/jwtdebug_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0883bd3f0829c5063022018f3e4e0c198b2fa97bcd52d17e842e293b418b3bf3"
      define_method(:install) do
        bin.install "jwtdebug"
      end
    end
  end

  test do
    system "#{bin}/jwtdebug --version"
  end
end
