# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwtdebug < Formula
  desc "A command line tool to decode, verify and generate JWTs (JSON Web Tokens)."
  homepage "github.com/rselbach/jwtdebug"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rselbach/jwtdebug/releases/download/v0.2.0/jwtdebug_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "0dc04d34e311bb47a575cc54cf1f701e0fb17dd44bd6d3a4081c774305c5fff1"

      def install
        bin.install "jwtdebug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rselbach/jwtdebug/releases/download/v0.2.0/jwtdebug_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a99b791cb449101a1c20588af83f2aecbccd471a37dea8b0bf57188297c01284"

      def install
        bin.install "jwtdebug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rselbach/jwtdebug/releases/download/v0.2.0/jwtdebug_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "516a25b55399861086bcd4b36c7f943bbba9b0715daaf9e6bd03117461d02e01"

        def install
          bin.install "jwtdebug"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rselbach/jwtdebug/releases/download/v0.2.0/jwtdebug_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "edbdca0279b6f917e2962da0aedd3763c3d54e732c2b4863ea4c32d2cd0c48ff"

        def install
          bin.install "jwtdebug"
        end
      end
    end
  end

  test do
    system "#{bin}/jwtdebug -version"
  end
end
