# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwtdebug < Formula
  desc "A command line tool to decode and debug JWTs (JSON Web Tokens)."
  homepage "https://github.com/rselbach/jwtdebug"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rselbach/jwtdebug/releases/download/v1.3.1/jwtdebug_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "99358ae50b924a41d2b76df114acfb71645a53246d71b91708552a322690fa77"

      define_method(:install) do
        bin.install "jwtdebug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rselbach/jwtdebug/releases/download/v1.3.1/jwtdebug_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "02dbdde6cf918140e306f4d6f710aab4ff6708783173cdb4cc27f03f2bc3f6f7"

      define_method(:install) do
        bin.install "jwtdebug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/jwtdebug/releases/download/v1.3.1/jwtdebug_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "d94b8eb3edf08e854e245f8da891e8a6770da603df3afe51d4968bcf3e26f8dc"
      define_method(:install) do
        bin.install "jwtdebug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/jwtdebug/releases/download/v1.3.1/jwtdebug_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7fb09ea7dbc485be6fc3699eb50612371a87477c737c51d48a5fc357f63613cc"
      define_method(:install) do
        bin.install "jwtdebug"
      end
    end
  end

  test do
    system "#{bin}/jwtdebug --version"
  end
end
