# This file was generated by GoReleaser. DO NOT EDIT.
cask "jwtdebug" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "683c6819a0518cb303f64e6c04c15fb34f5f54114a37a77e55616d61eeefd01e"
      url "https://github.com/rselbach/jwtdebug/releases/download/v#{version}/jwtdebug_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ac53f7a3e928f0a2f3cbbfadc6e791c02782382dea19b4c27708e4b1c57870bb"
      url "https://github.com/rselbach/jwtdebug/releases/download/v#{version}/jwtdebug_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2fc4b4c58c28db80bd841c2bd7a20f01f1b381e790b70a6d0ddd84d396f6ce36"
      url "https://github.com/rselbach/jwtdebug/releases/download/v#{version}/jwtdebug_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "15644cc720f80ee2fa8e8c8376bda6cca3fc68b5a39834169fe8f23b3c87318e"
      url "https://github.com/rselbach/jwtdebug/releases/download/v#{version}/jwtdebug_Linux_arm64.tar.gz"
    end
  end

  name "jwtdebug"
  desc "A command line tool to decode and debug JWTs (JSON Web Tokens)."
  homepage "https://github.com/rselbach/jwtdebug"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jwtdebug"

  # No zap stanza required

end
