# This file was generated by GoReleaser. DO NOT EDIT.
cask "jwtdebug" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "f8afce719d1ba58adc2bd756736187aa33164fac72c2ae48fd66a76dc3ef6398"
      url "https://github.com/rselbach/jwtdebug/releases/download/v#{version}/jwtdebug_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4dc80cfbbc4d461a0aaa158f0e866c4fb6070f351ad73eb380f56a66657ee10f"
      url "https://github.com/rselbach/jwtdebug/releases/download/v#{version}/jwtdebug_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "678d4042347d7de50b89177ef4dd18f465f87b1e2453d0c97dde6ec3234c81d3"
      url "https://github.com/rselbach/jwtdebug/releases/download/v#{version}/jwtdebug_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "51e363256807363131365e75730e6eccc8be7b4eb9c1138f9d5a5c88eddba8a3"
      url "https://github.com/rselbach/jwtdebug/releases/download/v#{version}/jwtdebug_Linux_arm64.tar.gz"
    end
  end

  name "jwtdebug"
  desc "A command line tool to decode and debug JWTs (JSON Web Tokens)."
  homepage "https://github.com/rselbach/jwtdebug"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jwtdebug"

  # No zap stanza required

end
