# This file was generated by GoReleaser. DO NOT EDIT.
cask "scimtest" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "7c606c5a31d643d339bf6fa2a52292339ff997b8dd9679299913bac8ca9131f2"
      url "https://github.com/rselbach/scimtest/releases/download/v#{version}/scimtest_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/rselbach/scimtest"
    end
    on_arm do
      sha256 "0fd57f5386a808ebf86f4c5d32261303c866a8184e4432472f7a6a10050606f3"
      url "https://github.com/rselbach/scimtest/releases/download/v#{version}/scimtest_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/rselbach/scimtest"
    end
  end

  on_linux do
    on_intel do
      sha256 "79d892df430b9ec644a6f94a219dfb97353689114448d48f46c774bb6d8d4340"
      url "https://github.com/rselbach/scimtest/releases/download/v#{version}/scimtest_#{version}_linux_amd64.tar.gz",
        verified: "github.com/rselbach/scimtest"
    end
    on_arm do
      sha256 "fa863826e016af64fc6954d4eddbfe578ffd6c5b7b49129eaba47f86acc3049e"
      url "https://github.com/rselbach/scimtest/releases/download/v#{version}/scimtest_#{version}_linux_arm64.tar.gz",
        verified: "github.com/rselbach/scimtest"
    end
  end

  name "scimtest"
  desc "Local SCIM/OIDC/SAML auth testing service"
  homepage "https://github.com/rselbach/scimtest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scimtest"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scimtest"]
    end
  end

  # No zap stanza required

end
