# This file was generated by GoReleaser. DO NOT EDIT.
cask "scimtest" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "cf957a0d9dc4e711c9432e78491297c13fc764f32598910879b47d6d179d7c27"
      url "https://github.com/rselbach/scimtest/releases/download/v#{version}/scimtest_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4219cc7ee2043fb56adcf50561dc33f8187a3125b760409e3a89e19a0f5d1c0b"
      url "https://github.com/rselbach/scimtest/releases/download/v#{version}/scimtest_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "90f6e02f6beb126ce7e42e64b69836995ed062ad96d697edf815a5155de5dd25"
      url "https://github.com/rselbach/scimtest/releases/download/v#{version}/scimtest_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f921ae1c704d712dacc499eb7d05d207420876640645f20dbd2f7c0e9e7b29b8"
      url "https://github.com/rselbach/scimtest/releases/download/v#{version}/scimtest_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scimtest"
  desc "Local SCIM/OIDC/SAML auth testing service"
  homepage "https://github.com/rselbach/scimtest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scimtest"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scimtest"]
    end
  end

  # No zap stanza required

end
