# This file was generated by GoReleaser. DO NOT EDIT.
cask "scimtest" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "a819150d6b85e91b1f421f73c4ded0edd71c4153d7a2779a3c847bcba9e20b27"
      url "https://github.com/rselbach/scimtest/releases/download/v#{version}/scimtest_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cce6cbea8c7cc1775406c50bcf03908babf7a03740e2f1505ee6c5d635fee19e"
      url "https://github.com/rselbach/scimtest/releases/download/v#{version}/scimtest_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dafddee1f540b50b0db4e828f2fcc51eb2495c33ff723cb0dc3ed68c539b835b"
      url "https://github.com/rselbach/scimtest/releases/download/v#{version}/scimtest_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "62e2a1f512247807b34ab437db1fd04393eb5c8d88fda1faeae271ae6aef2c36"
      url "https://github.com/rselbach/scimtest/releases/download/v#{version}/scimtest_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scimtest"
  desc "Local SCIM/OIDC/SAML auth testing service"
  homepage "https://github.com/rselbach/scimtest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scimtest"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scimtest"]
    end
  end

  # No zap stanza required

end
