# typed: false
# frozen_string_literal: true

# This file was generated by llm-usage release workflow. DO NOT EDIT.
class LlmUsage < Formula
  desc "Simple local usage report for Pi, Codex CLI, Claude Code, and OpenCode"
  homepage "https://github.com/rselbach/llm-usage"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rselbach/llm-usage/releases/download/v0.0.1/llm-usage_v0.0.1_darwin_amd64.tar.gz"
      sha256 "de1b487e3a5a57377c99948f27659d9bf7d04c07a7330aac3ab42d9bd5708177"
    end

    if Hardware::CPU.arm?
      url "https://github.com/rselbach/llm-usage/releases/download/v0.0.1/llm-usage_v0.0.1_darwin_arm64.tar.gz"
      sha256 "129333d4398e31970043416406bf92a65c931843dfcdeffab92ff0456d6d4b0b"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/llm-usage/releases/download/v0.0.1/llm-usage_v0.0.1_linux_amd64.tar.gz"
      sha256 "d71a73e3aff7b2051ba546a2d5c6cf857fb5088df4c8955cb74ee42118e3d0d5"
    end

    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/llm-usage/releases/download/v0.0.1/llm-usage_v0.0.1_linux_arm64.tar.gz"
      sha256 "e2f1896a6bd2ba0ec7a5ec99c6f045e91b89ff2789b430cea0a79f0b9f32ddd1"
    end
  end

  def install
    bin.install "llm-usage"
  end

  test do
    assert_match "Usage Report", shell_output("#{bin}/llm-usage --no-pricing --duration 1s")
  end
end
