# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rgrok < Formula
  desc "Small HTTP tunneling tool"
  homepage "https://github.com/rselbach/rgrok"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rselbach/rgrok/releases/download/v0.0.3/rgrok_0.0.3_darwin_amd64.tar.gz"
      sha256 "396bd3984242d282749c91b34cefb2c136fb72deacf98ca09c094f56b1f5f23c"

      define_method(:install) do
        bin.install "rgrok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rselbach/rgrok/releases/download/v0.0.3/rgrok_0.0.3_darwin_arm64.tar.gz"
      sha256 "c5a990effd67c752cecb6b028626d05fadb95492821fed5a232e5446dfca6abb"

      define_method(:install) do
        bin.install "rgrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/rgrok/releases/download/v0.0.3/rgrok_0.0.3_linux_amd64.tar.gz"
      sha256 "f758b0028a100e853864b4e04cb22e8b7ca7d03471f7a7c84fcdeb0b3341ed9c"
      define_method(:install) do
        bin.install "rgrok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/rgrok/releases/download/v0.0.3/rgrok_0.0.3_linux_arm64.tar.gz"
      sha256 "677a760225babae8a6620d49e4ad643ca1aea3660bc07e0b9fb8c2202e187689"
      define_method(:install) do
        bin.install "rgrok"
      end
    end
  end

  test do
    system "#{bin}/rgrok", "--help"
  end
end
