# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rgrok < Formula
  desc "Small HTTP tunneling tool"
  homepage "https://github.com/rselbach/rgrok"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rselbach/rgrok/releases/download/v0.0.2/rgrok_0.0.2_darwin_amd64.tar.gz"
      sha256 "dab7d75bf168d70a1fd87714d48baa7982f354455223d33372935e2af22b533d"

      define_method(:install) do
        bin.install "rgrok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rselbach/rgrok/releases/download/v0.0.2/rgrok_0.0.2_darwin_arm64.tar.gz"
      sha256 "f95548c149bc2adf708f0e1d46b31abd35fa2cea37992d857990ecd524d6cce1"

      define_method(:install) do
        bin.install "rgrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/rgrok/releases/download/v0.0.2/rgrok_0.0.2_linux_amd64.tar.gz"
      sha256 "cb29dc65355412a6197125092999b64454f1cb88cf720852bd061f42c170e179"
      define_method(:install) do
        bin.install "rgrok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/rgrok/releases/download/v0.0.2/rgrok_0.0.2_linux_arm64.tar.gz"
      sha256 "e6326ab30fd6378a128e7d4e5329c40f27a8fd1ac326fa0adcb0a46e0d4bd721"
      define_method(:install) do
        bin.install "rgrok"
      end
    end
  end

  test do
    system "#{bin}/rgrok", "--help"
  end
end
