# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rgrok < Formula
  desc "Small HTTP tunneling tool"
  homepage "https://github.com/rselbach/rgrok"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rselbach/rgrok/releases/download/v0.0.1/rgrok_0.0.1_darwin_amd64.tar.gz"
      sha256 "280bda1a5e8d9f13804dad9c0013feb0f33a449c3ce12025cd83296efcc405a7"

      define_method(:install) do
        bin.install "rgrok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rselbach/rgrok/releases/download/v0.0.1/rgrok_0.0.1_darwin_arm64.tar.gz"
      sha256 "a85aeb30bd0a3dd52528c92aab276f632e6ec693b72b631a20e4899c0dfe477e"

      define_method(:install) do
        bin.install "rgrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/rgrok/releases/download/v0.0.1/rgrok_0.0.1_linux_amd64.tar.gz"
      sha256 "f937e84d081609ecb4dc6e082d1ad6c197469d61bd2e65bcc00044ab04e633a6"
      define_method(:install) do
        bin.install "rgrok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/rgrok/releases/download/v0.0.1/rgrok_0.0.1_linux_arm64.tar.gz"
      sha256 "6c047a6e90a5eec09529acdd582f61a914b7a1f480fbbf14447c70db535b2cfe"
      define_method(:install) do
        bin.install "rgrok"
      end
    end
  end

  test do
    system "#{bin}/rgrok", "--help"
  end
end
