# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scimtest < Formula
  desc "Local SCIM/OIDC/SAML auth testing service"
  homepage "https://github.com/rselbach/scimtest"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rselbach/scimtest/releases/download/v0.0.3/scimtest_0.0.3_darwin_amd64.tar.gz"
      sha256 "be76e2a9b98d2ef8f1db98981592be1fa231152e8391bc2c58fe8b21c81c0f6a"

      define_method(:install) do
        bin.install "scimtest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rselbach/scimtest/releases/download/v0.0.3/scimtest_0.0.3_darwin_arm64.tar.gz"
      sha256 "e4fe5f7ed5f8fd493f003552eb510e378fb3a8d20e96438b6e852444ce2f8bd5"

      define_method(:install) do
        bin.install "scimtest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/scimtest/releases/download/v0.0.3/scimtest_0.0.3_linux_amd64.tar.gz"
      sha256 "05f8ff04b5aa65f2b97905f3355d7b99b406f2dd4b717a61e505a75446ea1e0c"
      define_method(:install) do
        bin.install "scimtest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/scimtest/releases/download/v0.0.3/scimtest_0.0.3_linux_arm64.tar.gz"
      sha256 "30a7039da007c2357bfbc077bdd26ddcdd061e7959bb7d967c336b1f008c683a"
      define_method(:install) do
        bin.install "scimtest"
      end
    end
  end

  test do
    system "#{bin}/scimtest", "--help"
  end
end
