# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scimtest < Formula
  desc "Local SCIM/OIDC/SAML auth testing service"
  homepage "https://github.com/rselbach/scimtest"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rselbach/scimtest/releases/download/v0.8.0/scimtest_0.8.0_darwin_amd64.tar.gz"
      sha256 "43b11112a7da7161805ba55045e91fc0cea5e3f922e26de0465bda8c28a1f68e"

      define_method(:install) do
        bin.install "scimtest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rselbach/scimtest/releases/download/v0.8.0/scimtest_0.8.0_darwin_arm64.tar.gz"
      sha256 "e461c9a9324f3b3b337fb1e2d02e1dbd90c374051f767af8af8453f994b63651"

      define_method(:install) do
        bin.install "scimtest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/scimtest/releases/download/v0.8.0/scimtest_0.8.0_linux_amd64.tar.gz"
      sha256 "98c736b1ddcebb93107145b316b7a329f07666ac30b5e1c44acdf16b4c478b6a"
      define_method(:install) do
        bin.install "scimtest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/scimtest/releases/download/v0.8.0/scimtest_0.8.0_linux_arm64.tar.gz"
      sha256 "d3a35b47b53344dc8218b80aad362aaace9c1b4912e85526d8e35cc1e044f6aa"
      define_method(:install) do
        bin.install "scimtest"
      end
    end
  end

  test do
    system "#{bin}/scimtest", "--help"
  end
end
