# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scimtest < Formula
  desc "Local SCIM/OIDC/SAML auth testing service"
  homepage "https://github.com/rselbach/scimtest"
  version "0.8.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rselbach/scimtest/releases/download/v0.8.2/scimtest_0.8.2_darwin_amd64.tar.gz"
      sha256 "8ac08133b9d8711e8122f658eafd8796025b861e8dd153af1fe797cf4c0bc4f7"

      define_method(:install) do
        bin.install "scimtest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rselbach/scimtest/releases/download/v0.8.2/scimtest_0.8.2_darwin_arm64.tar.gz"
      sha256 "19e4ea82b70cfad5a4c8726ae795f2b8d09404bc0096907970660d3fcc7f4a47"

      define_method(:install) do
        bin.install "scimtest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/scimtest/releases/download/v0.8.2/scimtest_0.8.2_linux_amd64.tar.gz"
      sha256 "aee71ed456c0f8dd2731fbdbfd3f20c1ce928d97558d7c23e435764597285200"
      define_method(:install) do
        bin.install "scimtest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rselbach/scimtest/releases/download/v0.8.2/scimtest_0.8.2_linux_arm64.tar.gz"
      sha256 "56e727d3949f2bd2f46ccf48c0ca28ec1a8b7745c975501cac28b579d394b8ff"
      define_method(:install) do
        bin.install "scimtest"
      end
    end
  end

  test do
    system "#{bin}/scimtest", "--help"
  end
end
